### ISSUE TITLE
vim syntax highlighting colors are off

### ISSUE THREAD

**Issue by ghost** [FreedomBen/screen-for-OSX#3]
Hi, I'm not sure if this has to do with your port or not but I am seeing a strange behavior where vim is running in a 256-color mode but the colors do not match what I have created in my vim colorscheme.  Is there anything added in the OSX patch that would have caused this?  Or is it a problem with screen itself.  The issue I'm seeing is identical to this:

http://superuser.com/questions/800126/gnu-screen-changes-vim-syntax-highlighting-colors

**Comment by ghost** [comment]
My apologies, the Apple-supplied screen was running instead of the locally built one.  Sorry!

**Comment by FreedomBen** [comment]
No problem!  Glad you got it figured out and thanks for following up :smile:
