### ISSUE TITLE
Install.sh Error

### ISSUE THREAD

**Issue by scirelli** [FreedomBen/screen-for-OSX#5]
I follow the instructions on how to install in your README.md and got 
`/autogen.sh: line 2: exec: autoreconf: not found`
I'm on El Capitan

**Comment by FreedomBen** [comment]
do you have the developer/command line tools installed?  If you open xcode I think it offers to install them if they aren't already there

**Comment by scirelli** [comment]
yes I have xcode installed. When I run xcode it just opens the Welcome to
Xcode splash screen. Anything else I need to check?

On Thu, Dec 17, 2015 at 1:54 PM, FreedomBen notifications@github.com
wrote:

> do you have the developer/command line tools installed? If you open xcode
> I think it offers to install them if they aren't already there
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreedomBen/screen-for-OSX/issues/5#issuecomment-165547104
> .

## 

Steve Cirelli
Cell: 347-618-1144
KK4FRG

Email Charter http://emailcharter.org/

**Comment by FreedomBen** [comment]
If you:

```
brew install automake
```

does that add the missing autoreconf?

**Comment by scirelli** [comment]
That worked! Thanks!

On Sat, Dec 26, 2015 at 7:29 PM, FreedomBen notifications@github.com
wrote:

> If you:
> 
> brew install automake
> 
> does that add the missing autoreconf?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreedomBen/screen-for-OSX/issues/5#issuecomment-167373101
> .

## 

Steve Cirelli
Cell: 347-618-1144
KK4FRG

Email Charter http://emailcharter.org/

**Comment by FreedomBen** [comment]
awesome, glad to hear it
